### ISSUE TITLE
Navbar Icons Not Visible 

### ISSUE THREAD

**Issue by Aarsh13** [jaiyankargupta/OCD-Website#378]
Description:
When hovering over the navbar items (About, Events, Resources, Links) or in dark mode, the icons associated with these items are not visible. 

**Steps to Reproduce:**
1. Navigate to the Open Code Developers (OCD) Website
2. Move the cursor over the navbar items (About, Events, Resources, Links)
3. Observe that no icons do not change color on hover

**Expected Behavior:**
Icons should appear or become more visible when hovering over navbar items

![image](https://github.com/user-attachments/assets/14a44747-1f98-4931-afa7-58f169ae0c98)

![image](https://github.com/user-attachments/assets/a6c71f9f-d2dd-4de1-be43-bed952851e81)

**Comment by priya10241** [comment]
@jaiyankargupta assign this issue to me

**Comment by jaiyankargupta** [comment]
@priya10241 done
