### ISSUE TITLE
Contributors not showing

### ISSUE THREAD

**Issue by Kharb-Hardik** [jaiyankargupta/OCD-Website#400]
on the contributor page the top contributors are not being shown and the dark mode is not working for that page
![image](https://github.com/user-attachments/assets/d1a8d081-8ab8-4024-9738-1da23037b68a)

**Comment by jaiyankargupta** [comment]
@Kharb-Hardik fix kroge ?

**Comment by Kharb-Hardik** [comment]
iska major part fetch calls ka hai aur vo mereko aati ni hai
